service: trains

provider:
  name: aws
  runtime: python3.6
  environment:
    DARWIN_TOKEN: ${env:DARWIN_TOKEN}
    WSDL: ${env:WSDL}

functions:
  stations:
    handler: handler.stations
    events:
      - http:
          path: stations
          method: get
          cors: true

  iot:
    handler: handler.iot
    events:
      - http:
          path: iot/{from}/{to}
          method: get
          cors: true
          request:
            parameters:
               paths:
                 from: true
                 to: true

  next:
    handler: handler.next
    events:
      - http:
          path: next/{from}/{to}
          method: get
          cors: true
          request:
            parameters:
               paths:
                 from: true
                 to: true

  departures:
    handler: handler.list
    events:
      - http:
          path: departures/{from}/{to}
          method: get
          cors: true
          request:
            parameters:
               paths:
                 from: true
                 to: true
plugins:
  - serverless-python-requirements
  - serverless-domain-manager

custom:
  pythonRequirements:
    dockerizePip: non-linux

  customDomain:
    domainName: trains.mcrlab.co.uk
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

package:
  exclude:
  - .circleci/**
  - .coverage
