version: '2.1'
orbs:
  python: circleci/python@2.1.1

jobs:
  build_and_test:
    working_directory: ~/python-ci
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest

workflows:
  build_and_test:
    jobs:
      - build_and_test

