# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build_and_test:
    working_directory: ~/python-ci

    docker:
      # specify the version you desire here
      - image: circleci/python:3.6.2-stretch-browsers

    steps:
      - checkout
      - run: sudo pip install -r requirements.txt
      - run:
          name: Install python test dependencies
          command: |
            sudo pip install nose
            sudo pip install coverage

      - run:
          name: Run tests with code coverage
          command: |
            nosetests --with-coverage

  deploy:
    working_directory: ~/python-ci

    docker:
      # specify the version you desire here
      - image: circleci/python:3.6.2-stretch-browsers

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-node-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-node
        # run tests
      # deploy app
      # this is slow. build a custom docker image and use that
      - run:
          name: Install node and npm
          command: |
            curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node --version && npm -v

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-node-{{ checksum "package.json" }}

      - run:
          name: Deploy application
          command: sls deploy -v

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
